version: "3.3"

services:
  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: springtestdb
      MYSQL_USER: newuser
      MYSQL_PASSWORD: password      
    ports:
      - "3307:3306"
  myserver:
    build: .
    ports:
      - "8084:8084"
    environment:
      DB_NAME: springtestdb
      DB_HOST: mysql-db
      DB_USERNAME: newuser
      DB_PASSWORD: password
    restart: on-failure #app will crash about 5 or 6 times before db set up is complete
    depends_on:
      - mysql-db

