---
apiVersion: v1
kind: Namespace
metadata:
  name: springboot-mysql
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: efs-csi-pvc
  namespace: springboot-mysql
#  annotations:
#    volume.beta.kubernetes.io/storage-class: "aws-efs"
spec:
  storageClassName: efs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

#---
#kind: PersistentVolumeClaim
#apiVersion: v1
#metadata:
#  namespace: optimo-dev
#  name: efs-claim
#spec:
#  storageClassName: efs
#  accessModes:
#  - ReadWriteMany
#  resources:
#    requests:
#      storage: 20Gi
