apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim
  namespace: static
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
