apiVersion: v1
kind: Namespace
metadata:
  name: static
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv
  namespace: static
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-046f99f1efd82bda6
