apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-boot-ingress
  namespace: springboot-mysql
  # annotations:
  #   kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
        - backend:
            service:
              name: my-app
              port: 
                number: 8080
          path: /
          pathType: Prefix
