apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-boot-ingress
  namespace: springboot-mysql
  # annotations:
  #   kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: a06e4dbdfc0e84ded9320875b9ad5c3b-1167032956.us-east-2.elb.amazonaws.com         #host is required by nginx 
    http:
      paths:
        - backend:
            service:
              name: my-app
              port: 
                number: 8080
          path: /
          pathType: Prefix
