pipeline {
    agent any
    tools {
        maven 'Maven'
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                echo "build stage"
                sh 'mvn clean install'
            }
        }
        stage('Test') {
            steps {
            sh
                sh './Jenkins/scripts/test.sh'
            }
        }
        stage('Deliver') {
            steps {
                nodejs('node') {
                    sh './Jenkins/scripts/deliver.sh'
                }
            }
        }
    }
}